# Generated by Django 2.1.5 on 2019-01-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('saddress', models.CharField(max_length=50)),
                ('smarks', models.IntegerField()),
            ],
            options={
                'db_table': 'stud',
            },
        ),
    ]
